conversational_development_indices:
  import_db: VERSION_DB
  import_query: >
    SELECT *
    FROM conversational_development_indices
    WHERE updated_at >= CURRENT_TIMESTAMP - interval '{days} day'
  export_db: EXPORT_DB
  export_schema: 'version'
  export_table: 'conversational_development_indices'
  export_table_schema:
    id: integer
    usage_data_id: integer
    leader_boards: double precision
    instance_boards: double precision
    leader_ci_pipelines: double precision
    instance_ci_pipelines: double precision
    leader_deployments: double precision
    instance_deployments: double precision
    leader_environments: double precision
    instance_environments: double precision
    leader_issues: double precision
    instance_issues: double precision
    leader_merge_requests: double precision
    instance_merge_requests: double precision
    leader_milestones: double precision
    instance_milestones: double precision
    leader_notes: double precision
    instance_notes: double precision
    leader_projects_prometheus_active: double precision
    instance_projects_prometheus_active: double precision
    leader_service_desk_issues: double precision
    instance_service_desk_issues: double precision
    created_at: timestamp without time zone
    updated_at: timestamp without time zone
    percentage_boards: double precision
    percentage_ci_pipelines: double precision
    percentage_deployments: double precision
    percentage_environments: double precision
    percentage_issues: double precision
    percentage_merge_requests: double precision
    percentage_milestones: double precision
    percentage_notes: double precision
    percentage_projects_prometheus_active: double precision
    percentage_service_desk_issues: double precision
  export_table_primary_key: id
fortune_companies:
  import_db: VERSION_DB
  import_query: >
    SELECT *
    FROM fortune_companies
    WHERE updated_at >= CURRENT_TIMESTAMP - interval '{days} day'
  export_db: EXPORT_DB
  export_schema: 'version'
  export_table: 'fortune_companies'
  export_table_schema:
    id: integer
    rank: integer
    company: character varying
    domain: character varying
    created_at: timestamp without time zone
    updated_at: timestamp without time zone
  export_table_primary_key: id
hosts:
  import_db: VERSION_DB
  import_query: >
    SELECT *
    FROM hosts
    WHERE updated_at >= CURRENT_TIMESTAMP - interval '{days} day'
  export_db: EXPORT_DB
  export_schema: 'version'
  export_table: 'hosts'
  export_table_schema:
    id: integer
    url: character varying
    created_at: timestamp without time zone
    updated_at: timestamp without time zone
    star: boolean
    fortune_rank: integer
    in_salesforce: boolean
  export_table_primary_key: id
licenses:
  import_db: VERSION_DB
  import_query: >
    SELECT *
    FROM licenses
    WHERE updated_at >= CURRENT_TIMESTAMP - interval '{days} day'
  export_db: EXPORT_DB
  export_schema: 'version'
  export_table: 'licenses'
  export_table_schema:
    id: integer
    company: character varying
    user_count: integer
    add_ons: character varying
    starts_on: date
    expires_on: date
    created_at: timestamp without time zone
    updated_at: timestamp without time zone
    active_users_count: integer
    historical_max_users_count: integer
    last_ping_received_at: timestamp without time zone
    version: character varying
  export_table_primary_key: id
schema_migrations:
  import_db: VERSION_DB
  import_query: >
    SELECT *
    FROM schema_migrations
  export_db: EXPORT_DB
  export_schema: 'version'
  export_table: 'schema_migrations'
  export_table_schema:
    version: character varying
  export_table_primary_key: version
usage_data:
  import_db: VERSION_DB
  import_query: >
    SELECT *
    FROM usage_data
    WHERE updated_at >= CURRENT_TIMESTAMP - interval '{days} day'
  export_db: EXPORT_DB
  export_schema: 'version'
  export_table: 'usage_data'
  export_table_schema:
    id: integer
    source_ip: character varying
    version: character varying
    active_user_count: integer
    installation_type: character varying
    historical_max_users: integer
    license_user_count: integer
    license_starts_at: timestamp without time zone
    license_expires_at: timestamp without time zone
    license_add_ons: character varying
    license_restricted_user_count: integer
    recorded_at: timestamp without time zone
    created_at: timestamp without time zone
    updated_at: timestamp without time zone
    counts: text
    license_id: integer
    stats: json
    mattermost_enabled: boolean
    uuid: character varying
    edition: character varying
    hostname: character varying
    host_id: integer
  export_table_primary_key: id
users:
  import_db: VERSION_DB
  import_query: >
    SELECT *
    FROM users
    WHERE updated_at >= CURRENT_TIMESTAMP - interval '{days} day'
  export_db: EXPORT_DB
  export_schema: 'version'
  export_table: 'users'
  export_table_schema:
    id: integer
    email: character varying
    sign_in_count: integer
    current_sign_in_at: timestamp without time zone
    last_sign_in_at: timestamp without time zone
    current_sign_in_ip: inet
    last_sign_in_ip: inet
    failed_attempts: integer
    locked_at: timestamp without time zone
    created_at: timestamp without time zone
    updated_at: timestamp without time zone
    provider: character varying
    uid: character varying
  export_table_primary_key: id
version_checks:
  import_db: VERSION_DB
  import_query: >
    SELECT *
    FROM version_checks
    WHERE updated_at >= CURRENT_TIMESTAMP - interval '{days} day'
  export_db: EXPORT_DB
  export_schema: 'version'
  export_table: 'version_checks'
  export_table_schema:
    id: integer
    request_data: text
    created_at: timestamp without time zone
    updated_at: timestamp without time zone
    gitlab_version: character varying
    referer_url: character varying
    host_id: integer
  export_table_primary_key: id
versions:
  import_db: VERSION_DB
  import_query: >
    SELECT *
    FROM versions
    WHERE updated_at >= CURRENT_TIMESTAMP - interval '{days} day'
  export_db: EXPORT_DB
  export_schema: 'version'
  export_table: 'versions'
  export_table_schema:
    id: integer
    version: character varying
    vulnerable: boolean
    created_at: timestamp without time zone
    updated_at: timestamp without time zone
  export_table_primary_key: id
