version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: weekly
    labels: [dependencies]
    groups:
      default:
        update-types:
        - "minor"
        - "patch"
    commit-message:
      prefix: "ci: "
    cooldown:
      default-days: 7
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
    labels: [dependencies]
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci: "
    cooldown:
      default-days: 7
  - package-ecosystem: uv
    versioning-strategy: increase-if-necessary
    directory: "/"
    schedule:
      interval: weekly
    labels: [dependencies]
    groups:
      development-dependencies:
        dependency-type: development
      runtime-dependencies:
        dependency-type: production
        update-types:
        - "minor"
        - "patch"
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(deps-dev): "
    cooldown:
      default-days: 7
    allow:
      - dependency-type: "all"
  - package-ecosystem: npm
    versioning-strategy: increase
    directory: "docs"
    schedule:
      interval: weekly
    labels: [dependencies]
    groups:
      docusaurus:
        patterns:
          - "docusaurus/**"
      development-dependencies:
        dependency-type: development
        exclude-patterns:
          - "docusaurus/**"
      runtime-dependencies:
        dependency-type: production
        exclude-patterns:
          - "docusaurus/**"
        update-types:
        - "minor"
        - "patch"
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(deps-dev): "
    cooldown:
      default-days: 7
  - package-ecosystem: "docker-compose"
    directory: "tests/fixtures/docker/"
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
