version: 2

enable-beta-ecosystems: true

multi-ecosystem-groups:
  python:
    commit-message:
      prefix: "fix(deps): "
      prefix-development: "chore(deps-dev): "
    schedule:
      interval: weekly

updates:
  - package-ecosystem: pip
    directory: "/.github/workflows"
    schedule:
      interval: weekly
      time: "12:00"
      timezone: "Etc/UTC"
      day: monday
    labels: [dependencies]
    groups:
      default:
        update-types:
        - "minor"
        - "patch"
    commit-message:
      prefix: "ci: "
    cooldown:
      default-days: 7

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "12:00"
      timezone: "Etc/UTC"
      day: monday
    labels: [dependencies]
    groups:
      actions:
        patterns:
          - "*"
    commit-message:
      prefix: "ci: "
    cooldown:
      default-days: 7

  - package-ecosystem: uv
    versioning-strategy: lockfile-only
    directory: "/"
    schedule:
      interval: weekly
      time: "12:00"
      timezone: "Etc/UTC"
      day: monday
    labels: [dependencies]
    groups:
      development-dependencies:
        dependency-type: development
      runtime-dependencies:
        dependency-type: production
        update-types:
        - "minor"
        - "patch"
    cooldown:
      default-days: 7
    multi-ecosystem-group: python
    patterns: ["*"]

  - package-ecosystem: pip
    versioning-strategy: increase-if-necessary
    directory: "/"
    schedule:
      interval: weekly
      time: "12:00"
      timezone: "Etc/UTC"
      day: monday
    labels: [dependencies]
    groups:
      development-dependencies:
        dependency-type: development
      runtime-dependencies:
        dependency-type: production
        update-types:
        - "minor"
        - "patch"
    cooldown:
      default-days: 7
    multi-ecosystem-group: python
    patterns: ["*"]

  - package-ecosystem: npm
    versioning-strategy: increase
    directory: "docs"
    schedule:
      interval: weekly
      time: "12:00"
      timezone: "Etc/UTC"
      day: monday
    labels: [dependencies]
    groups:
      development-dependencies:
        dependency-type: development
      runtime-dependencies:
        dependency-type: production
        update-types:
        - "minor"
        - "patch"
    commit-message:
      prefix: "chore(deps): "
      prefix-development: "chore(deps-dev): "
    cooldown:
      default-days: 7

  - package-ecosystem: "docker-compose"
    directory: "tests/fixtures/docker/"
    schedule:
      interval: "monthly"
      time: "12:00"
      timezone: "Etc/UTC"
    cooldown:
      default-days: 7
