ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.ci hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_commit_msg: "chore: pre-commit autoupdate"
  autoupdate_schedule: monthly
  skip:
    - uv-lock
    - check-github-discussion-templates
    - check-dependabot

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace
        exclude: ^src/meltano/core/cli_messages\.py$
      - id: end-of-file-fixer
        exclude: ^.*/plugins/.*/.*\.lock$
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args: ["--autofix", "--indent=2", "--no-sort-keys"]
      - id: check-added-large-files
        exclude: ^uv\.lock$
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements
      - id: no-commit-to-branch

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.35.0
    hooks:
      - id: check-metaschema
        name: validate JSON schemas against meta schemas
        files: ^src/meltano/schemas?/.*\.json$
      - id: check-jsonschema
        name: validate 'meltano.yml' with jsonschema
        files: .*/meltano.yml$
        args: ["--schemafile", "src/meltano/schemas/meltano.schema.json"]
      - id: check-github-issue-config
      - id: check-github-issue-forms
      - id: check-jsonschema
        alias: check-github-discussion-templates
        name: validate GitHub discussion templates
        files: ^.github/DISCUSSION_TEMPLATE/.*\.yml$
        args: ["--schemafile", "https://json.schemastore.org/github-discussion.json"]
      - id: check-compose-spec
      # TODO: Restore built-in check when https://github.com/SchemaStore/schemastore/pull/5167 ships into check-jsonschema
      # - id: check-dependabot
      - id: check-jsonschema
        alias: check-dependabot
        name: validate Dependabot configuration
        files: ^.github/dependabot\.yml$
        args: ["--schemafile", "https://json.schemastore.org/dependabot-2.0.json"]
      - id: check-github-actions
      - id: check-github-workflows

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.11.0.1
    hooks:
      - id: shellcheck
        name: shellcheck
        exclude: ^integration/mdsh$

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.55.0 # Keep this in sync with the eslint "additional_dependency" below!
    hooks:
      - id: eslint
        files: \.[jt]sx?$
        args: ['--fix', '--config=docs/.eslintrc.json']
        additional_dependencies:
          - "eslint@8.55.0" # Keep this in sync with the rev above!
          - "eslint-config-prettier@8.8.0"
          - "eslint-plugin-prettier@5.0.0"
          - "eslint-plugin-react@7.33.0"
          - "eslint-plugin-vue@9.15.1"
          - "prettier@3.0.0"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.8
    hooks:
    - id: ruff-check
      args: [--fix, --exit-non-zero-on-fix, --show-fixes]
    - id: ruff-format

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.15
    hooks:
      - id: uv-lock
