ci:
  autofix_commit_msg: |
    [pre-commit.ci] auto fixes from pre-commit.ci hooks

    for more information, see https://pre-commit.ci
  autofix_prs: true
  autoupdate_commit_msg: 'chore: pre-commit autoupdate'
  autoupdate_schedule: weekly

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
        # The `bumpversion` command fails to commit its own changes to
        # `.bumpversion.cfg` because it leaves some trailing whitespace.
        exclude: (^\.bumpversion\.cfg$|cli_messages\.py)
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-json
      - id: pretty-format-json
        args:
          - "--autofix"
          - "--indent=2"
          - "--no-sort-keys"
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-toml
      - id: debug-statements

  - repo: https://github.com/python-jsonschema/check-jsonschema
    rev: 0.21.0
    hooks:
      - id: check-metaschema
        files: ^schemas?/.*\.json$
      - id: check-jsonschema
        name: Validate 'meltano.yml' with jsonschema
        files: .*/meltano.yml$
        args:
          - "--schemafile"
          - "schema/meltano.schema.json"
      - id: check-jsonschema
        name: Validate 'discovery.yml' with jsonschema
        files: ^src/meltano/core/bundle/discovery.yml$
        args:
          - "--schemafile"
          - "schema/discovery.schema.json"

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.33.0 # Keep this in sync with the eslint "additional_dependency" below!
    hooks:
      - id: eslint
        files: \.([jt]sx?|vue)$
        entry: bash -c 'cd src/webapp && ARGS=("$@") && eslint --fix --config=.eslintrc.js "../../$0" "${ARGS[@]/#/../../}"'
        types: [file]
        require_serial: true
        additional_dependencies:
          - "@vue/eslint-config-prettier@7.0.0"
          - "@vue/babel-preset-app@5.0.8"
          - "@babel/eslint-parser@7.19.1"
          - "eslint@8.33.0" # Keep this in sync with the rev above!
          - "eslint-config-prettier@8.5.0"
          - "eslint-plugin-prettier@4.2.1"
          - "eslint-plugin-vue@9.8.0"
          - "prettier@2.8.1"

  - repo: https://github.com/psf/black
    rev: 22.12.0
    hooks:
      - id: black
        exclude: ^(src/meltano/migrations/)

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.3.1
    hooks:
      - id: pyupgrade
        args:
          - "--py3-plus"
          - "--py37-plus"
          - "--keep-mock"

  - repo: https://github.com/flakeheaven/flakeheaven
    rev: 3.2.1
    hooks:
      - id: flakeheaven
        exclude: ^(src/meltano/migrations/)
        additional_dependencies:
          - flake8==4.0.1
          - flake8-bandit==3.0.0
          - flake8-broken-line==0.4.0
          - flake8-bugbear==22.12.6
          - flake8-commas==2.1.0
          - flake8-comprehensions==3.10.1
          - flake8-debugger==4.1.2
          - flake8-docstrings==1.6.0
          - flake8-eradicate==1.4.0
          - flake8-isort==4.2.0
          - flake8-polyfill==1.0.2
          - flake8-quotes==3.3.1
          - flake8-rst-docstrings==0.2.7
          - flake8-string-format==0.3.0
          - pep8-naming==0.12.1
          - wemake-python-styleguide==0.16.1
