# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.3.0
  hooks:
    - id: trailing-whitespace
      # The `bumpversion` command fails to commit its own changes to
      # `.bumpversion.cfg` because it leaves some trailing whitespace.
      exclude: ^\.bumpversion\.cfg$
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-merge-conflict
    - id: check-toml
    - id: debug-statements
# - repo: https://github.com/pre-commit/mirrors-mypy
#   rev: v0.790
#   hooks:
#     - id: mypy
- repo: https://github.com/pre-commit/mirrors-eslint
  rev: v7.14.0
  hooks:
    - id: eslint
      files: '.(js|vue)'
      additional_dependencies:
        - '@vue/eslint-config-prettier@^4.0.1'
        - babel-eslint@^10.0.1
        - eslint-config-prettier@^3.3.0
        - eslint-plugin-prettier@^3.1.0
        - eslint-plugin-vue@^5.0.0
        - eslint@^5.16.0
        - prettier@^1.15.2

- repo: local
  hooks:
  - id: black
    name: black
    entry: poetry run black
    language: system
    types: [python]
    files: '.py'
  - id: flake8
    name: flake8
    entry: poetry run flake8
    language: system
    types: [python]
    files: '.py'
  - id: isort
    name: isort
    entry: poetry run isort
    language: system
    types: [python]
    files: '.py'
  - id: pyupgrade
    name: pyupgrade
    entry: poetry run pyupgrade
    language: system
    args:
    - "--py3-plus"
    - "--py36-plus"
    types: [python]
    files: '.py'
