# Default values for melt.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  ingress:
    enabled: true
    annotations: {}
    hosts:
      - chart-example.local
    tls:
      - secretName: melt-tls
        hosts:
          - chart-example.local
  oauth2-proxy:
    enabled: false

oauth2-proxy:
  enabled: false
  # clientId:
  # clientSecret:
  # cookieSecret:
  gitlabHost: https://gitlab.com

service:
  type: ClusterIP
  port: 80

image:
  repository: meltano/meltano
  tag: full
  pullPolicy: Always

database:
  postgresDatabase: postgres
  postgresUser: postgres
  # postgresPassword:

replicaCount: 1

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {} 

postgresql:
  install: true
  imageTag: 9.6.8
  # This should be configured until Postgres can properly handle secrets without generating new ones on upgrade
  postgresPassword: changeme
