name: Validate meltano yaml examples against the schema

on:
  pull_request:
    paths:
      - 'docs/example-library/**'
      - 'schema/meltano.schema.json'
  workflow_dispatch:
    inputs: {}

jobs:
  check_meltano_schema:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout the repository
      uses: actions/checkout@v3.0.2

    - name: Setup Python 3.8
      uses: actions/setup-python@v4.3.0
      with:
        python-version: 3.8
        architecture: x64

    - name: Install check-jsonschema
      run: |
        pipx install check-jsonschema
        check-jsonschema --version

    - name: Validate example meltano yaml files
      run: |
        check-jsonschema docs/example-library/*/meltano.yml docs/example-library/*/ending-meltano.yml --schemafile schema/meltano.schema.json
