.build_base:
  extends:
  - .docker_build
  - .parallel:python_version
  stage: build-base
  needs: []
  variables:
    DOCKERFILE: docker/base/Dockerfile
    IMAGE_NAME: $CI_REGISTRY_IMAGE/base
    PYTHON_IMAGE_VERSION: 'echo $PYTHON_VERSION | cut -d "." -f1-2}'
  before_script:
    - source .gitlab/ci/scripts/docker_build_before_script.sh
    - export EXTRA_ARGS="--build-arg PYTHON_VERSION=$PYTHON_VERSION"
    - export IMAGE_TAG=$BASE_SHA-python$PYTHON_IMAGE_VERSION

# the meltano base should only be rebuild when the `requirements.txt` file
# has a change, and should be inferable from the `BASE_SHA` environment
# variable

# Manages:
#  - meltano/meltano/base:<base_sha>-python<version>
meltano_base:
  extends: .build_base
  only:
    changes:
      - docker/base/Dockerfile
      - poetry.lock
      - pyproject.toml

# Manages:
#  - <fork namespace>/meltano/base:<base_sha>-python<version>
meltano_base_forks:
  extends: .build_base
  except:
    - branches@meltano/meltano
    - tags@meltano/meltano
