.only:version-tags:
  only:
    refs:
      - tags@meltano/meltano
    variables:
      - $CI_COMMIT_TAG =~ /^v*/

.only:master:
  only:
    refs:
      - master@meltano/meltano

.parallel:python_version:
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.6", "3.7", "3.8"]
