.only:version-tags:
  only:
    refs:
      - tags@meltano/meltano
    variables:
      - $CI_COMMIT_TAG =~ /^v*/

.only:release-branches:
  only:
    refs:
      # TODO: Replace with /^release\/v.*$/
      - /^2895.*$/

.only:master:
  only:
    refs:
      - master@meltano/meltano

.parallel:python_version:
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.6", "3.7", "3.8", "3.9"]

.parallel:image_tag_suffix:
  parallel:
    matrix:
      - IMAGE_TAG_SUFFIX: ["", "-python3.6", "-python3.7", "-python3.8", "-python3.9"]
