.only:version-tags:
  only:
    refs:
      - tags@meltano/meltano
    variables:
      - $CI_COMMIT_TAG =~ /^v*/

.only:release-branches:
  only:
    refs:
      - /^release\/v.*$/

.only:master:
  only:
    refs:
      - master@meltano/meltano

.parallel:python_version:
  parallel:
    matrix:
      - PYTHON_VERSION: ["3.7", "3.8", "3.9"]

.parallel:python_image_version:
  parallel:
    matrix:
      - PYTHON_IMAGE_VERSION: ["3.7", "3.8", "3.9"]

.parallel:image_tag_suffix:
  parallel:
    matrix:
      - IMAGE_TAG_SUFFIX: ["", "-python3.7", "-python3.8", "-python3.9"]

.windows:defaults:
  variables:
    PYTHONIOENCODING: utf-8
